DESIGN_NAME: prbs31
VERILOG_FILES:
- dir::../src/prbs31.v

# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# SDC files
#PNR_SDC_FILE: dir::chip_top.sdc
#SIGNOFF_SDC_FILE: dir::chip_top.sdc
#FALLBACK_SDC: dir::chip_top.sdc

# Power / ground nets
VDD_NETS:
- VDD
GND_NETS:
- VSS

# Clock
CLOCK_PORT: clk
CLOCK_PERIOD: 5 # 200 MHz

# Overfix hold violations
PL_RESIZER_HOLD_SLACK_MARGIN: 0.35
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.3

# Increase density for more 
# logic on your die
PL_TARGET_DENSITY_PCT: 70
GRT_ALLOW_CONGESTION: true

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

# Absolute die size
#FP_SIZING: absolute
#DIE_AREA: "0 0 100 100"

IO_PIN_ORDER_CFG: dir::pin_order.cfg

# Fix antenna violations after DRT
DRT_ANTENNA_REPAIR_ITERS: 10
DRT_ANTENNA_REPAIR_MARGIN: 10 # %

# Since we cannot meet the minimum density limit on Metal2,
# ignore active metal on previous and subsequent layers
# (DM.5_DM.7 and DM.4_DM.6). Dummy metal is moved to active
# metal during the precheck.
KLAYOUT_FILLER_OPTIONS:
  Metal2_ignore_active: true

# Because we have multiple power pads for one power domain
MAGIC_EXT_UNIQUE: notopports

# Image render settings
KLAYOUT_RENDER_RESOLUTION: 2048
KLAYOUT_RENDER_OVERSAMPLING: 3
KLAYOUT_PROPERTIES: dir::gf180mcu_render.lyp

# DRC settings
# A high number of workers increases RAM usage,
# but can significantly improve the performance.
# workers * threads should equal the available
# hardware threads for a best possible utilization.

KLAYOUT_DRC_THREADS: 1

# "max" equals max hardware threads
KLAYOUT_DRC_OPTIONS:
  decks: "all,-antenna,-density,-cup" # disable CUP for now
  variant: ref::$PDK
  workers: max

KLAYOUT_DENSITY_OPTIONS:
  decks: "density"
  variant: ref::$PDK
  workers: max

KLAYOUT_ANTENNA_OPTIONS:
  decks: "antenna"
  variant: ref::$PDK
  workers: max
